services:
  readme-backend:
    build:
      dockerfile: ./Dockerfile
      target: debug
      args:
        UV_EXTRA_ARGS: "--extra debug"
    develop:
      watch:
        - action: sync
          path: ./python/src
          target: /app
        - action: rebuild
          path: ./golang/src
        - action: sync
          path: ./resources
          target: /app/resources
        - action: rebuild
          path: uv.lock
    ports:
      - 80:80
    volumes:
      - ./data:/app/data
    environment:
      GITHUB_PROFILE_URL: "http://localhost/readme.md"
