services:
  readme-backend:
    build:
      dockerfile: ./Dockerfile
      target: debug
      args:
        UV_EXTRA_ARGS: "--extra debug"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app
        - action: sync
          path: ./resources
          target: /app/resources
        - action: sync
          path: ./readme.example.html
          target: /app/readme.example.html
        - action: rebuild
          path: ./requirements.txt
    ports:
      - 80:80
    environment:
      GITHUB_PROFILE_URL: "http://localhost/readme.md"
