name: lint

on:
  # workflow_dispatch: 
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    name: check ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: 'python'
      - name: Install latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Install tox
        run: uv sync --only-group tox --frozen --python 3.13
      - name: Run tox for python ${{ matrix.python-version }}
        run: uv run tox -e py${{ matrix.python-version }}
